name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / erb_lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_bundler
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/using_bundler/Gemfile
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: erb_lint with skip install and using bundler
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          skip_install: 'true'
          use_bundler: 'true'
          reporter: github-pr-annotations
          fail_level: warning
      - run: |
          test "$(bundle exec erb_lint --version)" == "0.9.0"
